language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: Q7QB1A0OMIKN0wqmHvExvSwgXsq8iLGwR+Q6fvWBNThWOUvaDdQGPa0WDZjHVsgcjcnbibpo7P5TkMF8lWkfW51Z57aDK1zSz2v5urp8yp/pQnO9UX9df4N8mTaUD//Uhz0REun8XWkIvV/fcPBHybs6text1zswdnPlSaaYL/o=
  - secure: TFguADNREf4yLR4z2FlPYLEvtdKnQWzAX9GrtjUxEyAtFmHX1yyFFzr9mWYNhIUlYypjlFaIxN4015OtqNDV5cA2DEWqYzu9LUvdbGL9fMhaiTmeuiyUS5C495L8Lk17gq1n0j4pVn+CBzB0q6PvT/GUmCj7Wn+vp/vb3RjA1l8=
